### PR TITLE
.BRA Update: Alpha, anim speed & output

### PR DESCRIPTION
**Pull request by adrot**
Thanks for the github! Yes, I'm Adrot from our Youtube talks. I have asked around for some modifications to output the .BRA animations and I've got some good help. The changes do the following:
-The Animation viewer has the correct speed (150 instead of 100)
-Will automatically output the opened .BRA animation as PNG frames in a folder where the Debug/Released binaries are, called ''output''. (Should probably had rather made a button for that, but I have no idea how...). To note, putting another BRA in the program to view will override previous outputted frames in the folder, except those with a higher number than the frame numbers of the new animation.
-Will round up Alpha values, as they were multiples of 36. This made the sprites look semi transparent.

The only thing missing now is rounding up the RGB values, as the grays are slightly different from the accurate values. To note for the future the requirement I was told, ''there needs to be an additional set of code to multiply the RGB colors accordingly. Since 248's the limit for those, you'd have to add 1 for after each group of 16''. The change would probably need to be done in the LWBRF file.

I am a complete 0 at knowing C#, so my quest continues, but we are close. 5+ years I waited for this moment... Exciting times!

### CODE REVIEW

**Comment by Jas2o** [comment]
Thanks for the pull request, I've never actually had to handle one of these before so I hope I've done the right thing here.

- Have accepted the changes for viewer speed and alpha (some tweaks).
- Have gone in a different direction for saving the BRA frames. Yesterday I had added a button that saves to an Export folder with the frame files named after the input file (can still result in overwriting for different characters).

**Comment by adrot** [comment]
I want to update on some new findings.
There is a potential problem code regarding RGB values. Specifically in your FRM.cs file. The helper that gave me the tip is not experienced in C# files, but he told me that there could be certain wrong values in the following part of the code:
```csharp        public static Color Palette2Color(ushort palette) {
            ushort hex = Tools.SwapBytes(palette);
            int R = (hex & 0x1F) * 8;
            int G = (hex >> 5 & 0x1F) * 8;
            int B = (hex >> 10 & 0x1F) * 8;
```

They told me that it should probably fixed to the following:
```csharp int R0 = (hex & 0x1F);
            int R = (R0<<3)|(R0>>2);
            int G0 = (hex >> 5 & 0x1F);
            int G = (G0<<3)|(G0>>2);
            int B0 = (hex >> 10 & 0x1F);
            int B = (B0<<3)|(B0>>2);
```
Using this fix, I have obtained some fantastic results. Besides the anti alias border pixels, comparing the resulted sprite with the correct RGB values sprite from GLIntercept, has shown that there are no wrong pixels.
OUT

Would this help?

Update:

I would like to add that, when I put the RGB code in the old version that had the Alpha rounding code that I added (aka the one that  wasn't tweaked by you), and compared both the tool's frame with GLIntercept frame, I had a perfect match. No pixel mismatch:
OUTV1

Some exception happened with sprites of colors...
Hugh1 (GLIntercept)
Char_Spec (GLIntercept)
Hugh2 (KyleHyde)
Char_Spec (KyleHyde)
OUT
Comparison.

I cannot fully confirm how meaningful the visual impact is in this case.

**Comment by Jas2o** [comment]
Have made the suggested changes, admittedly I haven't tested it but sure looks like you're striving and better equip  for accuracy check. I'm failing to see how the switch and if got different alpha results but have changed that back.

Six years of getting no where with the BRA format and then suddenly getting close enough in 2020 was enough to kill the project for me.

**Comment by adrot** [comment]
I can offer u the BRA files and images to compare if u want to. I can't guarantee I have a lot of GLIntercept pictures to compare, but I can find and make them where necessary due to already made save files for each chapter. Other small issues with some pixels have surfaced in some black and white sprite animations, but I have yet to know how to tackle them. Best case scenario, the community doesn't care, but I will do offer a disclaimer to be on the safe side.

Personally, I started this since around...probably around 2015-2016. Sometime later I found your blog and ever since, I tried to find some help in understanding it, but alas, I failed. So I went the GLIntercept route to get all Hotel Dusk sprites, and I finally did so around 2018. Easy cause no tiles. However, the same cannot be said about Last Window in terms of success cause of the tile aspect. If one can find out Last Window's Debug Menu cheat code like in Hotel Dusk, it would make all this easy. The Debug's files was in Main_Debug, the script.ifb.
The rest of my introduction, you can find it as an issue in the NTR github page, without including the Cing Wiki admin part too. Wasn't sure how to reach you, but glad I finally did.

**Comment by Jas2o** [comment]
I'm actually off work this week! Send me some samples and I'll see what I can do about the pixel issues.

Might sus out if possible to get Last Window's debug menu loaded.

**Comment by Jas2o** [comment]
I've been staring at Last Window a bit today and gotten nowhere with trying to load the debug menu, I have absolutely no idea how to use Ghidra or read ASM. Nothing really stands out except it looks very different to Hotel Dusk. Can't make sense of script.ifb files.

In terms of file names/extensions, the only game I can find mentioned on the internet is 'Cross of Venus' but nothing on if it has a working debug menu. Excluding Mobiclip can't see any clear links between the developers of that and Last Window.

**Comment by adrot** [comment]
I have yet to gather the more offending samples on the .BRA issue, so hang tight.
I want also to send you how I managed to eventually get what I needed to decipher .ebp and .bpg, most of what's in them at least, and also send you a tool used regarding unpacking and packing Script files in a convenient manner. The one condition is to not distribute the tool (it is not made by me and it is not publicly available), but you can reverse engineer it. Is that ok with you?

I recommend studying the cheat codes of Hotel Dusk, especially the Debug Menu one. However, due to the fact that we are struggling with .pack here, I am not 100% sure where the script.ifb would be located, or if studying it would work. Tinke has a part of it that shows each file's ID and Offset, might be of some assistance. I've never managed to spot Hotel Dusk's Debug menu in any case. Desmume has a Memory Viewer and other additional tools to help view the RAM. You could do a full dump from there and see the hex and the like, but it would create a 10+GB monster.

Action Replay cheat codes are created by modifying game code to change certain aspects of the game. To create a cheat code, you will need to identify the portion of code you want to modify and understand how to make the desired changes.

Here are some general steps to create an Action Replay cheat code:

- Determine the game and console for which you want to create the cheat code.
- Obtain a list of existing cheat codes for that game, as well as any available documentation on the game's code.
- Use a game console emulator or hardware cheat device to analyze the game code and identify the portion you want to modify.
- Use a hex editor or other tool to modify the code, making the desired changes.
- Test the modified code in the emulator or cheat device to ensure that it works as intended.
- Convert the modified code into an Action Replay format and save it as a new cheat code.

Note that creating cheat codes can be complex and time-consuming, and modifying game code can potentially lead to unintended consequences or even damage to your game or console. Always use caution and follow instructions carefully when creating or using cheat codes.

I have toyed a bit shamelessly with ChatGPT to read the Hotel Dusks Debug menu cheat code from Europe, and I got this:

The Action Replay cheat code you provided has four lines, each consisting of eight characters (4 bytes) representing hexadecimal values. Here is a breakdown of each line:

1. 0200B470 E3550092

- 0200B470: This is the memory address that the code is modifying.

- E3550092: This is the value that is being written to that memory address. In this case, it is a machine code instruction that tells the Nintendo DS to jump to a different part of memory and execute some code there.

2. 94000130 FFFB0000

- 94000130: This is another machine code instruction that tells the Action Replay device to pause execution for a short period of time.

- FFFB0000: This is the amount of time to pause, in hexadecimal format. In this case, it is a negative value that causes the Action Replay to pause for a long time, effectively stopping the game's execution.

3. 0200B470 E3A05004

0200B470: This is the same memory address as before.
E3A05004: This is another machine code instruction that sets a register to a specific value. In this case, it is setting the "r5" register to the value "4".

4. D2000000 00000000

- D2000000: This is the final machine code instruction that tells the Nintendo DS to return to normal execution.

- 00000000: This is just a filler value and has no effect on the code.

Together, these four lines of code modify the game's memory to jump to a different part of the code where the Debug Menu is located, pause execution to ensure that the jump is successful, set a register to a specific value, and then return to normal execution.

**Comment by Jas2o** [comment]
The script.ifb files are packed? Sure I'm interested to see anything new. I already tried studying Hotel Dusk's action replay code but the two games are different enough that I couldn't find the same function and make the same change.

I don't believe Github has any private messaging, but you can message me on Reddit: u/Logan2o

**Comment by Jas2o** [comment]
Oh ifb was just Zlib, haven't looked much at one uncompressed but excited to see something different.

I'll see about jazzing up the app interface to be a little less awkward for exploring rather than individually dumping a file and then opening in a hex editor.

**Comment by Jas2o** [comment]
Early app interface change, no more drag/drop and popup windows BUT that does mean the old interface is currently still needed for mass .pack extract. The idea being you could load a folder that has all the extracted packs then arrow key through the images. Would do more, but I should sleep.

Have added .ifb's getting decompressed and displayed on the Hex tab, will poke a bit another day. Hope to look at .bpg soon to get more of them displaying.

Interface20230403

**Comment by Jas2o** [comment]
Replaced the Zlib decompression code, the missing parts of .bpg should be resolved now.

Example-BPG

**Comment by adrot** [comment]
I had been moving slowly with the samples while u went ahead with those formats, so am gonna send u the tools and what I gathered from bpg and ebp. Files will be deleted after 3 days.
https://litter.catbox.moe/mrgj2y.7z
Public tool used for bpg and ebp: https://www.vg-resource.com/thread-28596.html

**Comment by Jas2o** [comment]
Thanks for sharing! Have downloaded a copy. Have fixed one type of ebp (BGRA8888).

Example-EBP-BGRA8888

**Comment by adrot** [comment]
I have paused my ongoing comparison with GLIntercept as I assume that the other monochrome animation sprites might yield same results. My findings so far are as follows:

-The entire cast of Memo characters from the Notepad menu are not to be trusted, especially on the bottom part of the sprites. I have compared Alpha channels by extracting them, and haven't seen a problem there, most likely could be RGB value issue.
-Most of Grab, Get, Look, Hand animations are not to be trusted. Especially on the grey outlines.
-Additional white pixel issues on monochrome characters are considered to be widespread and are likely to just affect the white outline's edges of the characters.
-Main_Note and System are probably safe, I have not found any issues on them so far. It is quite hard to assemble sprites for these, because as you advance further into the animation, their tile pattern changes.

I have also added the results of comparisons. As always, red pixels indicate where the issues are, you can layer with the sprite in order to pinpoint the source better. I lack the time to get the hex numbers of the colors atm. It is possible that the tiling issue could be solved by searching in the RAM, but it's beyond my limited knowledge. An interesting way to extract the watercolor graphics on the zoomed in characters was found with [MelonRipper](https://github.com/scurest/MelonRipper). 
Attempt:
Untitled 001
It's imperfect due to reasons such as the edges, and having to use the Bake function in Blender to make this real, but at least it was an honest attempt.
I recommend giving it a look sometime, as it has the ability to take a 3D Screenshot, and import said screenshot to Blender. A revolutionary finding of recent times, highly useful to get those pesky 3D Maps out.
I learned from them how to zoom out the 3D camera too in an [issue](https://github.com/scurest/MelonRipper/issues/2).

But enough sidetracking, zip with samples and comparison is here:
[Comparison.zip](https://github.com/Jas2o/KyleHyde/files/11163402/Comparison.zip)

**Pull request merged**
